# Inserts a blank line between shell prompts
add_newline = true

[directory]
truncation_length = 8

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[cmd_duration]
min_time = 500
format = "underwent [$duration](bold yellow)"

[git_branch]
symbol = "ğŸŒ± "
truncation_symbol = ""

[git_commit]

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"


[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]

[hostname]
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

[jobs]
symbol = "+ "
threshold = 4


[memory_usage]
# disabled = false

# [package]
format = "via [ğŸ $version](208 bold) "


[docker_context]
# format = "via [ğŸ‹ $context](blue bold)"

[rlang]
# format = "with [ğŸ“ $version](blue bold) "


[ruby]
symbol = "ğŸ”º "


[rust]
format = "via [âš™ï¸ $version](red bold)"

[terraform]
[sudo]
[status]
[shell]
[os]
[nodejs]
[python]
[deno]
[aws]
[username]
